
import com.google.code.bing.search.schema.web.WebResult;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import java.util.List;
import javax.imageio.ImageIO;
import javax.swing.JPanel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author He
 */
public class BingResultDisplayGUI extends javax.swing.JFrame {

    private List<WebResult> results = null;
    int iter = 0;
    /**
     * Creates new form BingResultDisplayGUI
     */
    public BingResultDisplayGUI(List<WebResult> wr) {
        results = wr;
        initComponents();
        if (wr.isEmpty()) {
            nextResult.setEnabled(false);
            previousResult.setEnabled(false);
            titleText.setText("No results available for search!");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        bingLogo = bingLogo = new BKGPanel();
        titleText = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descriptionURL = new javax.swing.JTextArea();
        nextResult = new javax.swing.JButton();
        previousResult = new javax.swing.JButton();
        exitButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("BING");

        bingLogo.setBackground(new java.awt.Color(204, 255, 255));

        javax.swing.GroupLayout bingLogoLayout = new javax.swing.GroupLayout(bingLogo);
        bingLogo.setLayout(bingLogoLayout);
        bingLogoLayout.setHorizontalGroup(
            bingLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        bingLogoLayout.setVerticalGroup(
            bingLogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 198, Short.MAX_VALUE)
        );

        titleText.setText("      ");

        descriptionURL.setEditable(false);
        descriptionURL.setColumns(20);
        descriptionURL.setFont(new java.awt.Font("Times New Roman", 0, 16)); // NOI18N
        descriptionURL.setLineWrap(true);
        descriptionURL.setRows(5);
        descriptionURL.setWrapStyleWord(true);
        jScrollPane1.setViewportView(descriptionURL);

        nextResult.setText("Next Result");
        nextResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextResultActionPerformed(evt);
            }
        });

        previousResult.setText("Previous Result");
        previousResult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                previousResultActionPerformed(evt);
            }
        });

        exitButton.setText("Exit");
        exitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(exitButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 507, Short.MAX_VALUE)
                        .addComponent(previousResult)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nextResult))
                    .addComponent(jScrollPane1)
                    .addComponent(titleText, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bingLogo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bingLogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(titleText, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nextResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(previousResult, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(exitButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitButtonActionPerformed
        dispose();
    }//GEN-LAST:event_exitButtonActionPerformed

    private void nextResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextResultActionPerformed
        loadNextResult();
    }//GEN-LAST:event_nextResultActionPerformed

    private void previousResultActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_previousResultActionPerformed
        loadPreviousResult();
    }//GEN-LAST:event_previousResultActionPerformed

    private void loadNextResult() {
        if (iter == results.size() - 1) {
            nextResult.setEnabled(false);
            return;
        } else {
            previousResult.setEnabled(false);
            WebResult wr = results.get(++iter);
            titleText.setText(wr.getTitle());
            String descText = "URL: " + wr.getUrl() + System.lineSeparator() + "Description: " + wr.getDescription();
            descriptionURL.setText(descText);
        }
    }
    
    private void loadPreviousResult() {
        if (iter == 0) {
            previousResult.setEnabled(false);
            return;
        } else {
            nextResult.setEnabled(true);
            WebResult wr = results.get(--iter);
            titleText.setText(wr.getTitle());
            String descText = "URL: " + wr.getUrl() + System.lineSeparator() + "Description: " + wr.getDescription();
            descriptionURL.setText(descText);
        }
    }
    
    private static class BKGPanel extends JPanel {
        
        @Override
        public void paintComponent(Graphics graphics) {
            super.paintComponent(graphics);
            Graphics2D g = (Graphics2D) graphics;
            g.drawImage(bkgImage, 0, 0, 754, 444, this);
        }
    }
    
    static BufferedImage bkgImage = null;
    static {
        try {
            bkgImage = ImageIO.read(new File("img/bing.png"));
            bkgImage = toBufferedImage(bkgImage.getScaledInstance(760, 198, Image.SCALE_SMOOTH));
        } catch (IOException e) {
            e.printStackTrace();
        }
    }
    
        /**
     * Converts a given Image into a BufferedImage
     * 
     * CREDIT https://code.google.com/p/game-engine-for-java/source/browse/src/com/gej/util/ImageTool.java#31
     *
     * @param img The Image to be converted
     * @return The converted BufferedImage
     */
    private static BufferedImage toBufferedImage(Image img) {
        if (img instanceof BufferedImage) {
            return (BufferedImage) img;
        }

        // Create a buffered image with transparency
        BufferedImage bimage = new BufferedImage(img.getWidth(null), img.getHeight(null), BufferedImage.TYPE_INT_ARGB);

        // Draw the image on to the buffered image
        Graphics2D bGr = bimage.createGraphics();
        bGr.drawImage(img, 0, 0, null);
        bGr.dispose();

        // Return the buffered image
        return bimage;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bingLogo;
    private javax.swing.JTextArea descriptionURL;
    private javax.swing.JButton exitButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton nextResult;
    private javax.swing.JButton previousResult;
    private javax.swing.JLabel titleText;
    // End of variables declaration//GEN-END:variables
}
