
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author He
 */
public class OptionsGUI extends javax.swing.JFrame {

    private MainGUI main;

    /**
     * Creates new form OptionsGUI
     */
    public OptionsGUI(MainGUI main) {
        this.main = main;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        bkgPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        difficultySelect = new javax.swing.JComboBox();
        showResultsOver = new javax.swing.JRadioButton();
        showResultsQuestion = new javax.swing.JRadioButton();
        apply = new javax.swing.JButton();
        cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);

        jLabel1.setText("Select difficulty:");

        difficultySelect.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Beginner", "Easy", "Medium", "Hard" }));
        difficultySelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                difficultySelectActionPerformed(evt);
            }
        });

        buttonGroup1.add(showResultsOver);
        showResultsOver.setSelected(true);
        showResultsOver.setText("Show results after entire quiz is over");
        showResultsOver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultsOverActionPerformed(evt);
            }
        });

        buttonGroup1.add(showResultsQuestion);
        showResultsQuestion.setText("Show results after every question");
        showResultsQuestion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                showResultsQuestionActionPerformed(evt);
            }
        });

        apply.setText("Apply");
        apply.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                applyActionPerformed(evt);
            }
        });

        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bkgPanelLayout = new javax.swing.GroupLayout(bkgPanel);
        bkgPanel.setLayout(bkgPanelLayout);
        bkgPanelLayout.setHorizontalGroup(
            bkgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(bkgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(showResultsQuestion)
                    .addComponent(jLabel1)
                    .addComponent(difficultySelect, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showResultsOver))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, bkgPanelLayout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(apply, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        bkgPanelLayout.setVerticalGroup(
            bkgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bkgPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(difficultySelect, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showResultsOver)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(showResultsQuestion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addGroup(bkgPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apply)
                    .addComponent(cancel))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bkgPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void applyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_applyActionPerformed
        if (main.isModifiable()) {
            main.setDifficulty(difficultySelect.getSelectedIndex());
            if (showResultsOver.isSelected()) {
                main.setQuestionHandling(0);
            } else if (showResultsQuestion.isSelected()) {
                main.setQuestionHandling(1);
            }
            System.out.println("Settings set: Difficulty="
                    + main.getDifficulty() + " QuestionHandling=" + main.getQuestionHandling());
            setVisible(false);
        } else {
            JOptionPane.showMessageDialog(null,
                    "Please finish the current quiz before modifying the options", "Invalid Change", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_applyActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        setVisible(false);
    }//GEN-LAST:event_cancelActionPerformed

    private void difficultySelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_difficultySelectActionPerformed
        // main.setDifficulty(difficultySelect.getSelectedIndex());
    }//GEN-LAST:event_difficultySelectActionPerformed

    private void showResultsOverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultsOverActionPerformed
        // main.setQuestionHandling(0);
    }//GEN-LAST:event_showResultsOverActionPerformed

    private void showResultsQuestionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_showResultsQuestionActionPerformed
        // main.setQuestionHandling(1);
    }//GEN-LAST:event_showResultsQuestionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton apply;
    private javax.swing.JPanel bkgPanel;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox difficultySelect;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton showResultsOver;
    private javax.swing.JRadioButton showResultsQuestion;
    // End of variables declaration//GEN-END:variables
}
